# Generated by Django 5.1.2 on 2024-10-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Livro')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('editora', models.CharField(max_length=255, verbose_name='Editora')),
                ('ano_publicacao', models.PositiveIntegerField(verbose_name='Ano de Publicação')),
                ('genero', models.CharField(choices=[('Ficção', 'Ficção'), ('Não-Ficção', 'Não-Ficção'), ('Romance', 'Romance'), ('Ciência', 'Ciência')], max_length=20, verbose_name='Gênero')),
                ('quantidade_total', models.PositiveIntegerField(verbose_name='Quantidade Total')),
                ('quantidade_disponivel', models.PositiveIntegerField(verbose_name='Quantidade Disponível')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Adicionar Livro',
            },
        ),
    ]
