# Generated by Django 5.1.2 on 2024-10-30 21:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={},
        ),
        migrations.AddField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(blank=True, null=True, verbose_name='Data do Empréstimo')),
                ('data_devolucao_prevista', models.DateField(blank=True, null=True, verbose_name='Data de Devolução Prevista')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=10, verbose_name='Status do Empréstimo')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Adicionar Empréstimo',
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(default=datetime.date.today, verbose_name='Data de Devolução')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('emprestimo', models.OneToOneField(limit_choices_to={'status': 'EM_ABERTO'}, on_delete=django.db.models.deletion.CASCADE, to='app.emprestimo', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name_plural': 'Devolver Empréstimo',
            },
        ),
    ]
